# str Accessor

The `.str` accessor in Pandas allows you to apply string methods to every value in a Series without using loops.

In [2]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "john doe",
        "ALICE SMITH",
        "Rohit Patel"
    ]
})
df

          Name
0     john doe
1  ALICE SMITH
2  Rohit Patel

In [5]:
df["Name"].str.upper()

0       JOHN DOE
1    ALICE SMITH
2    ROHIT PATEL
Name: Name, dtype: object

In [6]:
df["Name"].str.lower()

0       john doe
1    alice smith
2    rohit patel
Name: Name, dtype: object

# Case Conversion

Case conversion methods are used to change the letter casing of text, making data consistent and easier to analyze.

In [7]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "john doe",
        "ALICE SMITH",
        "rOhIt pAtEl",
        "jaNe"
    ]
})
df

          Name
0     john doe
1  ALICE SMITH
2  rOhIt pAtEl
3         jaNe

In [8]:
# Lower
df["Name"].str.lower()

0       john doe
1    alice smith
2    rohit patel
3           jane
Name: Name, dtype: object

In [9]:
# Upper
df["Name"].str.upper()

0       JOHN DOE
1    ALICE SMITH
2    ROHIT PATEL
3           JANE
Name: Name, dtype: object

In [10]:
# Title:- Capitalize the 1st letter of every word
df["Name"].str.title()

0       John Doe
1    Alice Smith
2    Rohit Patel
3           Jane
Name: Name, dtype: object

In [11]:
# Capitalize only the 1st letter of entire string 
df["Name"].str.capitalize()

0       John doe
1    Alice smith
2    Rohit patel
3           Jane
Name: Name, dtype: object

# Removing Extra Spaces

The `strip()`, `lstrip()`, and `rstrip()` methods are used to remove unwanted spaces from the beginning and/or end of strings.

In [12]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "  John Doe  ",
        " Alice ",
        "   Rohit Patel",
        "Jane   "
    ]
})
df

             Name
0      John Doe
1          Alice
2     Rohit Patel
3         Jane

In [13]:
 # .strip() :-Removes spaces from both the beginning and the end of a string.
df["Name"].str.strip()

0       John Doe
1          Alice
2    Rohit Patel
3           Jane
Name: Name, dtype: object

In [16]:
#.rstrip():- Removes spaces only from the right (end).
df["Name"].str.rstrip()

0          John Doe
1             Alice
2       Rohit Patel
3              Jane
Name: Name, dtype: object

In [15]:
# .lstrip() :- Removes spaces only from the left (beginning).
df["Name"].str.lstrip()

0     John Doe
1         Alice
2    Rohit Patel
3        Jane
Name: Name, dtype: object

In [18]:
df["Name"] = df["Name"].str.strip().str.title()
df

          Name
0     John Doe
1        Alice
2  Rohit Patel
3         Jane

# Searching Text

The `contains()`, `startswith()`, and `endswith()` methods are used to search for specific text patterns in a Pandas Series.

In [19]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "John Doe",
        "Alice Smith",
        "Rohit Patel",
        "Jane Doe"
    ],
    "Email": [
        "john@gmail.com",
        "alice@yahoo.com",
        "rohit@gmail.com",
        "jane@outlook.com"
    ]
})
df

          Name             Email
0     John Doe    john@gmail.com
1  Alice Smith   alice@yahoo.com
2  Rohit Patel   rohit@gmail.com
3     Jane Doe  jane@outlook.com

In [21]:
# .contains() :- Checks whether a string contains a given pattern.
df["Email"].str.contains("gmail")

0     True
1    False
2     True
3    False
Name: Email, dtype: bool

In [23]:
df[df["Email"].str.contains("gmail")]

          Name            Email
0     John Doe   john@gmail.com
2  Rohit Patel  rohit@gmail.com

In [24]:
# .startswith():- Checks whether a string starts with a given text.
df["Email"].str.startswith("john")

0     True
1    False
2    False
3    False
Name: Email, dtype: bool

In [25]:
df["Name"].str.startswith("J")

0     True
1    False
2    False
3     True
Name: Name, dtype: bool

In [26]:
# .endswith():- Checks whether a string ends with a given text.
df["Email"].str.endswith(".com")

0    True
1    True
2    True
3    True
Name: Email, dtype: bool

In [27]:
df["Name"].str.endswith("Doe")

0     True
1    False
2    False
3     True
Name: Name, dtype: bool

# split()

The `split()` method splits each string into multiple parts based on a specified separator.

In [32]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "John Doe",
        "Alice Smith",
        "Rohit Patel",
        "Jane Brown"
    ],
    "Email": [
        "john@gmail.com",
        "alice@yahoo.com",
        "rohit@gmail.com",
        "jane@outlook.com"
    ]
})
df

          Name             Email
0     John Doe    john@gmail.com
1  Alice Smith   alice@yahoo.com
2  Rohit Patel   rohit@gmail.com
3   Jane Brown  jane@outlook.com

In [33]:
df["Name"].str.split()

0       [John, Doe]
1    [Alice, Smith]
2    [Rohit, Patel]
3     [Jane, Brown]
Name: Name, dtype: object

In [34]:
df["Email"].str.split("@")

0      [john, gmail.com]
1     [alice, yahoo.com]
2     [rohit, gmail.com]
3    [jane, outlook.com]
Name: Email, dtype: object

In [38]:
df["Name"].str.split(expand=True)  #expand=True tells Pandas:
# "Instead of returning a list, create separate columns."

       0      1
0   John    Doe
1  Alice  Smith
2  Rohit  Patel
3   Jane  Brown

In [39]:
df[["First_Name","Last_Name"]]=df["Name"].str.split(expand=True)
df

          Name             Email First_Name Last_Name
0     John Doe    john@gmail.com       John       Doe
1  Alice Smith   alice@yahoo.com      Alice     Smith
2  Rohit Patel   rohit@gmail.com      Rohit     Patel
3   Jane Brown  jane@outlook.com       Jane     Brown

In [41]:
df["Domain"] = df["Email"].str.split("@").str[1] #.str[1] selects the second element (the domain).
df

          Name             Email First_Name Last_Name       Domain
0     John Doe    john@gmail.com       John       Doe    gmail.com
1  Alice Smith   alice@yahoo.com      Alice     Smith    yahoo.com
2  Rohit Patel   rohit@gmail.com      Rohit     Patel    gmail.com
3   Jane Brown  jane@outlook.com       Jane     Brown  outlook.com

# replace()

The `replace()` method replaces specified text in each string with new text.

In [42]:
import pandas as pd
df = pd.DataFrame({
    "Name": [
        "John Doe",
        "Alice Smith",
        "Rohit Patel",
        "Jane Doe"
    ],
    "Gender": [
        "Male",
        "Female",
        "Male",
        "Female"
    ],
    "Email": [
        "john@gmail.com",
        "alice@yahoo.com",
        "rohit@gmail.com",
        "jane@outlook.com"
    ]
})
df

          Name  Gender             Email
0     John Doe    Male    john@gmail.com
1  Alice Smith  Female   alice@yahoo.com
2  Rohit Patel    Male   rohit@gmail.com
3     Jane Doe  Female  jane@outlook.com

In [44]:
df["Gender"].str.replace("Male","M")

0         M
1    Female
2         M
3    Female
Name: Gender, dtype: object

In [45]:
df["Gender"].str.replace("Female","F")

0    Male
1       F
2    Male
3       F
Name: Gender, dtype: object

In [46]:
df["Gender"] = (
    df["Gender"]
      .str.replace("Male", "M")
      .str.replace("Female", "F")
)
df

          Name Gender             Email
0     John Doe      M    john@gmail.com
1  Alice Smith      F   alice@yahoo.com
2  Rohit Patel      M   rohit@gmail.com
3     Jane Doe      F  jane@outlook.com

In [47]:
df["Email"].str.replace("gmail", "googlemail")

0     john@googlemail.com
1         alice@yahoo.com
2    rohit@googlemail.com
3        jane@outlook.com
Name: Email, dtype: object

In [48]:
df["Name"].str.replace(" ", "_")

0       John_Doe
1    Alice_Smith
2    Rohit_Patel
3       Jane_Doe
Name: Name, dtype: object

In [50]:
df["Gender"].replace({     #Series Replacement
    "Male": "M",
    "Female": "F"
})
#For entire-value replacements, Series.replace() is cleaner than chaining multiple .str.replace() calls.

0    M
1    F
2    M
3    F
Name: Gender, dtype: object

# slice()

The `slice()` method extracts a portion of each string based on the specified start and stop positions.
df["Column"].str.slice(start, stop)

In [52]:
import pandas as pd
df = pd.DataFrame({
    "Employee_ID": [
        "EMP1001",
        "EMP1002",
        "EMP1003",
        "EMP1004"
    ],
    "Name": [
        "John Doe",
        "Alice Smith",
        "Rohit Patel",
        "Jane Brown"
    ]
})
df

  Employee_ID         Name
0     EMP1001     John Doe
1     EMP1002  Alice Smith
2     EMP1003  Rohit Patel
3     EMP1004   Jane Brown

In [54]:
df["Employee_ID"].str.slice(0,3)

0    EMP
1    EMP
2    EMP
3    EMP
Name: Employee_ID, dtype: object

In [55]:
df["Employee_ID"].str.slice(3)

0    1001
1    1002
2    1003
3    1004
Name: Employee_ID, dtype: object

In [56]:
df["Name"].str.slice(0,4)

0    John
1    Alic
2    Rohi
3    Jane
Name: Name, dtype: object

# extract()

The `extract()` method extracts text from strings using a regular expression (regex) and returns the matched parts.

In [57]:
import pandas as pd
df = pd.DataFrame({
    "Employee": [
        "EMP1001",
        "EMP2050",
        "EMP9876",
        "EMP1234"
    ],
    "Email": [
        "john@gmail.com",
        "alice@yahoo.com",
        "rohit@gmail.com",
        "jane@outlook.com"
    ]
})
df

  Employee             Email
0  EMP1001    john@gmail.com
1  EMP2050   alice@yahoo.com
2  EMP9876   rohit@gmail.com
3  EMP1234  jane@outlook.com

In [58]:
df["Employee"].str.extract(r"(\d+)")

      0
0  1001
1  2050
2  9876
3  1234

In [59]:
df["Employee"].str.extract(r"([A-Za-z]+)")

     0
0  EMP
1  EMP
2  EMP
3  EMP

In [60]:
df["Email"].str.extract(r"(.+)@")

       0
0   john
1  alice
2  rohit
3   jane

In [61]:
df["Email"].str.extract(r"@(.+)")

             0
0    gmail.com
1    yahoo.com
2    gmail.com
3  outlook.com

In [62]:
import pandas as pd
customers = pd.DataFrame({
    "Name": [
        "  john doe  ",
        "ALICE SMITH",
        "rOhIt pAtEl",
        " jane brown "
    ],
    "Email": [
        "JOHN@GMAIL.COM",
        " alice@yahoo.com ",
        "ROHIT@GMAIL.COM",
        "jane@OUTLOOK.COM"
    ],
    "Gender": [
        "Male",
        "Female",
        "Male",
        "Female"
    ]
})
customers

           Name              Email  Gender
0    john doe       JOHN@GMAIL.COM    Male
1   ALICE SMITH   alice@yahoo.com   Female
2   rOhIt pAtEl    ROHIT@GMAIL.COM    Male
3   jane brown    jane@OUTLOOK.COM  Female

In [66]:
customers["Name"] = (
    customers["Name"]
        .str.strip()
        .str.title()
)

customers["Email"] = (
    customers["Email"]
        .str.strip()
        .str.lower()
)

customers["Gender"] = customers["Gender"].replace({
    "Male": "M",
    "Female": "F"
})

customers["Domain"] = customers["Email"].str.split("@").str[1]
customers

          Name             Email Gender       Domain
0     John Doe    john@gmail.com      M    gmail.com
1  Alice Smith   alice@yahoo.com      F    yahoo.com
2  Rohit Patel   rohit@gmail.com      M    gmail.com
3   Jane Brown  jane@outlook.com      F  outlook.com